name: aem_plot

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets
  - mkl
  - simpeg
  - pyvista
  - pip:
    - git+https://github.com/simpeg/geoana.git
    - git+https://github.com/simpeg/simpeg.git@em1d_updates


