name: aem_plot

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - numpy=1.20.0
  - scipy=1.4.1
  - matplotlib
  - jupyter
  - ipywidgets
  - mkl
  - simpeg
  - pyvista
  - pip:
    - git+https://github.com/simpeg/simpeg.git@em1d_updates


